# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

jobs:
- job: C
  steps:
  - script: 'echo ##vso[task.setVariable skip;isOutput=true;]false'
    name: printvar

# Create a variable
  - bash: |
      echo "##vso[task.setvariable variable=sauce;isOutput=true]crushed tomatoes"
    name: printsauce

# Use the variable
# "$(sauce)" is replaced by the contents of the `sauce` variable by Azure Pipelines
# before handing the body of the script to the shell.
  - bash: |
      echo my pipeline variable is $(sauce)
- job: A
  dependsOn: C
  condition: and(succeeded(),ne(dependencies.C.outputs['printvar.skip'],'true'))
  variables:
    myjobvar: $[ dependencies.C.outputs['printsauce.sauce'] ]
  steps:
  - bash: | 
        echo "my job variable is $(myjobvar)"
    displayName: Echo Message
- job: B
  dependsOn: A
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - script: |
        lsb_release -a 
    displayName: Echo Message on Ubuntu18.04