# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

jobs:
- job: C
  steps:
  - script: 'echo ##vso[task.setVariable skip;isOutput=true;]false'
    name: printvar
- job: A
  dependsOn: C
  condition: and(succedded(),ne(dependencies.C.outputs['printvar.skip'],'true'))
  steps:
  - script: | 
        echo "$PRINTVAR"
        lsb_release -a 
    displayName: Echo Message
- job: B
  dependsOn: A
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - script: |
        lsb_release -a 
    displayName: Echo Message on Ubuntu18.04